### ISSUE TITLE
Support values other than true/false

### ISSUE THREAD

**Issue by wpsmithtwc** [jscs-dev/gulp-jscs#101]
Currently, this does not support all the options from the following:

It forces an array for [requireSpaceBeforeBinaryOperators](http://jscs.info/rule/requireSpaceBeforeBinaryOperators), [disallowSpaceAfterPrefixUnaryOperators](http://jscs.info/rule/disallowSpaceAfterPrefixUnaryOperators), [disallowSpaceBeforePostfixUnaryOperators](http://jscs.info/rule/disallowSpaceBeforePostfixUnaryOperators) when `true` is allowed.

It forces an true/false for [requireCamelCaseOrUpperCaseIdenifiers](http://jscs.info/rule/requireCamelCaseOrUpperCaseIdentifiers) or [disallowSpacesInsideObjectBrackets](http://jscs.info/rule/disallowSpacesInsideObjectBrackets), [disallowSpacesInsideObjectBrackets](http://jscs.info/rule/disallowSpacesInsideObjectBrackets) when string and objects are allowed.

There are probably others, but nonetheless....

**Comment by sindresorhus** [comment]
It supports anything JSCS supports. Try its issue tracker instead.
