### ISSUE TITLE
Implement different reporters

### ISSUE THREAD

**Issue by lukaszfiszer** [jscs-dev/gulp-jscs#21]
I'd be very useful to be able to configure and use different reporters. I plan to submit a PR implementing it, but as is quite a important feature, I'd prefer to discuss it before:

* linting and reporting should be separated: `$.jscs()` and `$.jscs.reporter('my-reporter')` (similarly to https://github.com/spenceralger/gulp-jshint) 
* we cannot use `node-jscs` reporters directly - they all write output to `console.log`, so they need to be ported and modified
* `checkstyle` and `xunit` reporter should combine all errors in a single single, vinyl file object. They shouldn't emit error event despite linting errors (use case: CI reports)
* other reporters should fail when linting errors occur
* support for custom reporters 

What are your thoughts?

**Comment by sindresorhus** [comment]
https://github.com/jscs-dev/gulp-jscs/pull/57 implemented the first stage for reporter supporting, an `jscs` object attached to the file object with some reporter data.

Next step is implementing:

- [ ] reporter fetching (depends on https://github.com/jscs-dev/node-jscs/issues/867)
- [ ] built-in fail reporter

**Comment by UltCombo** [comment]
@sindresorhus what's left for you to tick that first checkbox?

Guess I'll give this a stab tonight.

**Comment by UltCombo** [comment]
#66

**Comment by jamesmorgan** [comment]
+1 this would be nice

**Comment by idefy** [comment]
Until this is available, you should look at this plugin that allows to use jshint reporters:
https://github.com/gonsfx/gulp-jscs-stylish
