### ISSUE TITLE
Recursive jscs limited to 16 files?

### ISSUE THREAD

**Issue by jforzano** [jscs-dev/gulp-jscs#42]
I'm not sure if I'm doing something wrong, but when I feed an array of sources to gulp.src that includes a wildcard that recursively results in more than sixteen files, jscs only checks the first 16 files it encounters. An example src : `./assets/js/**/*.js`

Though if I run jscs from the command line with that source, it hits all the files.

**Comment by deniscostadsc** [comment]
I'm facing something similar to this issues at my project. Anything new?

**Comment by maxkfranz** [comment]
Ditto

Task:

```js
gulp.task('format', function(){
  return gulp.src('src/**/*.js')
    .pipe( jscs({
      fix: true,
      configPath: '.jscsrc'
    }) )
    .pipe( gulp.dest('formatted') ) // TODO move to src after confirming .jscsrc
  ;
});
```

```
npm ls orchestrator
cytoscape@2.5.0-unstable /Users/user/Documents/workspace/cytoscape.js
└─┬ gulp@3.9.0
  └── orchestrator@0.3.7 
```

**Comment by sindresorhus** [comment]
Gonna close as we're using gulp exactly as documented. Anything not working is with gulp/streams/etc, but not with this plugin.

**Comment by slavede** [comment]
I didn't quite understand why this was closed. What's the workaround to make this work?
