### ISSUE TITLE
Allow config file to be found by searching up through parent folders.

### ISSUE THREAD

**Issue by ntdaley** [jscs-dev/gulp-jscs#52]
When jscs is run from the command line, if a config file is not specified it's default behaviour is to look for a config file in the current directory, then its parent, grandparent, ... until it finds one.

This doesn't seem to be possible through this plugin.  Because the plugin assumes that if a path is not given that settings are going to be provided directly with no config file.

Perhaps it could be changed so that if no configPath is given (and no options) that it would call loadConfigFile.load without the configPath, so that it would search up through parents.  I don't think doing this would cause problems for existing gulpfiles, because currently in this scenario it would be looking in the current folder for .jscsrc; with this change it would be looking in the current folder before looking in parent folders.

Doing something like this in index.js should do the job.

```
if (Object.keys(options).length === 0) {
		checker.configure(loadConfigFile.load(configPath));
} else {
		checker.configure(options);
}
```

**Comment by sindresorhus** [comment]
[Fixed in 3.0.0](https://github.com/jscs-dev/gulp-jscs/releases/tag/v3.0.0)
