### ISSUE TITLE
Add filter function

### ISSUE THREAD

**Issue by Aetet** [jscs-dev/gulp-jscs#60]
Hello! In my project I have large legacy codebase, so I cannot lint whole files. I want lint only specific ranges of the file and search errors in it. 
For example I have file:
```javascript
function hello () {
  return +'4';
}

function hello2 () {
  return +'5';
}
```
jscs will fail on following loc: 2 and 6. But I want to ignore error in 6 loc. Is it possible to add filter function [here](https://github.com/jscs-dev/gulp-jscs/blob/master/index.js#L69) which will take error and vinyl file object and then decide add error or not?

**Comment by sindresorhus** [comment]
You can do any transformation you want in the stream before the jscs plugin. Like removing those lines before linting. You can also handle the error and check if it occurred only on those lines, if so ignore it.

**Comment by Aetet** [comment]
I cannot handle error, because it emit string and not javascript object, that I can handle
```javascript
errors.explainError(err, true)
```

**Comment by sindresorhus** [comment]
@Aetet https://github.com/jscs-dev/gulp-jscs#results

**Comment by Aetet** [comment]
Sorry. I used outdated version. Thanks for reply.
