### ISSUE TITLE
no color in output

### ISSUE THREAD

**Issue by Pomax** [jscs-dev/gulp-jscs#62]
I'm trying to run jscs using gulp-jscs without color in the error output because despite my terminal accepting the gulp coloring just fine, jscs output is a mess of `\[32` style ANSI strings instead of actual color. I know the jscs CLI can be told to use --no-color but for the life of me I can't figure out how to make the gulp-jscs task do the same. There's no mention in the docs anywhere, and no amount of Google or Stackoverflow is getting me any closer to an answer =)

**Comment by arthurvr** [comment]
> I know the jscs CLI can be told to use --no-color

And so can Gulp. Doesn't `$ gulp task --no-color` work for you?

**Comment by Pomax** [comment]
no idea, we've moved to npm scripts since I filed this, so I'll just close this issue and if someone else ever runs into it again they'll be in a better place to help debug than I am now. Thanks for revisiting though!
