### ISSUE TITLE
gulp-jscs doesn't output anything when used in gulp-watch pipeline

### ISSUE THREAD

**Issue by Tomalak** [jscs-dev/gulp-jscs#65]
**Full disclosure:** I'm not sure this is a gulp-jscs problem. This is a [crosspost from StackOverflow](http://stackoverflow.com/questions/28220905/).

```javascript
var gulp = require('gulp');
var jshint = require('gulp-jshint');
var jscs = require('gulp-jscs');
var watch = require('gulp-watch');

var paths = {
        scripts: ['./js/*.js']
    }    
var jscsRunner = jscs({
        disallowMixedSpacesAndTabs: true // etc
    });    
var jshintRunner = jshint({
        browser: true // etc
    });

// this outputs messages from jshint no problem
gulp.task('jshint', function() {
    return gulp.src(paths.scripts)
    .pipe(jshintRunner)
    .pipe(jshint.reporter('default'));
});

// this outputs messages from jscs no problem
gulp.task('jscs', function() {
    return gulp.src(paths.scripts)
    .pipe(jscsRunner);
});

// this only outputs messages from jshint
gulp.task('watch', function() {
    return watch(paths.scripts)
    .pipe(jscsRunner)
    .pipe(jshintRunner)
    .pipe(jshint.reporter('default'));
});
```

The problem is that when I run `gulp watch` I get no output from jscs, but when I run `gulp jscs` it works. 

So it seems to be connected to gulp-watch. Either that or I'm missing something really stupid here, in which case I'd be glad if you could help me out.

**Comment by UltCombo** [comment]
What gulp-watch version are you using? There are huge differences between 2.x, 3.x and 4.x.

**Comment by Tomalak** [comment]
```javascript
  "devDependencies": {
    "gulp": "^3.8.10",
    "gulp-jscs": "^1.4.0",
    "gulp-jshint": "^1.9.0",
    "gulp-watch": "^4.1.0",
    "jshint-stylish": "^1.0.0",
    "lazypipe": "^0.2.2"
  }
```

**Comment by UltCombo** [comment]
Currently, gulp-jscs only emits errors when the readable stream that is being piped into it ends, and your code is using gulp-watch's "endless stream" mode. I believe the callback mode is more suited for your needs:

```js
gulp.task('watch', function() {
    return watch(paths.scripts, function(files) {
        files
          .pipe(jscsRunner)
          .pipe(jshintRunner)
          .pipe(jshint.reporter('default'));
    });
});
```

**Comment by Tomalak** [comment]
@UltCombo Sounds good, but unfortunately doesn't work.

I think that is because `files` (`file`, really, in the callback there only ever is exactly one) is not a stream of `vinyl` objects, it's a single object. However, jscs expects a stream and crashes when it gets a file.

**Comment by UltCombo** [comment]
Oh I see, my bad. I thought the argument was still a stream (as it was in 3.x) because in my real use cases I still use gulp-batch:

```js
var batch = require('gulp-batch');
gulp.task('watch', function() {
    return watch(paths.scripts, batch(function(files) {
        return files
            .pipe(jscsRunner)
            .pipe(jshintRunner)
            .pipe(jshint.reporter('default'));
    }));
});
```

I've hastily adapted this code removing gulp-batch for the previous comment without knowing that the argument type has changed. The code with gulp-batch should work though. There are cleaner ways around this, of course -- I'll post one when I get home.

**Comment by Tomalak** [comment]
I'll wait. I've tried (and failed) to construct a single-object readable stream from the file, but my node experience so far is rather limited.

**Comment by UltCombo** [comment]
You can use [stream-array](https://github.com/mimetnet/node-stream-array) (or [event-stream's `readArray`](https://github.com/dominictarr/event-stream#readarray-array)) to make things easier:

```js
var streamify = require('stream-array');
gulp.task('watch', function() {
    return watch(paths.scripts, function(file) {
        streamify([file])
            .pipe(jscsRunner)
            .pipe(jshintRunner)
            .pipe(jshint.reporter('default'));
    });
});
```

**Comment by Tomalak** [comment]
Now we're getting somewhere. 

Your suggestion still isn't complete, though. jscs throws errors when it finds style violations and these errors need to be handled or gulp will crash.

Here is what I use now.

```javascript

var gulp = require('gulp');
var jshint = require('gulp-jshint');
var jscs = require('gulp-jscs');
var watch = require('gulp-watch');
var lazypipe = require('lazypipe');
var streamify = require('stream-array');

var paths = {
  scripts: ['./js/*.js']
};

var lintTasks = lazypipe()
    .pipe(jshint, {
        // ...
    })
    .pipe(jshint.reporter, 'jshint-stylish');

var jscsTasks = lazypipe()
    .pipe(jscs, {
        // ...
    });

gulp.task('watch', function() {
    return watch(paths.scripts, function(file) {
        streamify([file])
        .pipe(jscsTasks())
        .on('error', function (error) {
            console.log(error.toString());
        })
        .emit('end');
    })
    .pipe(lintTasks());
});
```

**Comment by UltCombo** [comment]
Oh yes, that's another detail I forgot -- gulp-batch wraps the callback in a domain so the error handler wouldn't be necessary if you were using gulp-batch.

Also should note that you won't need to use the callback style nor catch errors after #66 is merged.

**Comment by UltCombo** [comment]
Correction: if you were using gulp-batch the error would be suppressed by default, you'd need to supply an error handle to gulp-batch in order to log the error message as well.

**Comment by Tomalak** [comment]
Nice. For the moment I have something that works and I'll follow #66.
