### ISSUE TITLE
Unknown node type JSXElement

### ISSUE THREAD

**Issue by geraldyeo** [jscs-dev/gulp-jscs#71]
Getting this message with gulp-jscs. Possibly related to https://github.com/facebook/esprima/commit/2d47a78dc50a8cce10bcef7730a0e81f7782f2d2 ?

```package.json
[package.json]
...
"devDependencies": {
    "esprima-fb": "^13001.1001.0-dev-harmony-fb",
    "gulp": "^3.8.11",
    "gulp-jscs": "^1.4.0",
  }
...
```

```gulpfile.js
[gulpfile.js]
...
gulp.task('jscs', function() {
	return gulp.src([
			'./app/**/*.js'
		])
		.pipe(jscs());
});
...
```

**Comment by sindresorhus** [comment]
From the top of the readme:

> *Issues with the output should be reported on the jscs [issue tracker](https://github.com/jscs-dev/node-jscs/issues).*
