### ISSUE TITLE
Allow passing a jscs as an option

### ISSUE THREAD

**Issue by timkelty** [jscs-dev/gulp-jscs#72]
It would be nice to be able to pass your own jscs instance as an option, instead of using this module's jscs dep.

Otherwise, if there are updates to jscs you want and you're using gulp-jscs, you have to wait for an update or make  PR.

**Comment by sindresorhus** [comment]
Nope. That wouldn't work if JSCS does any breaking changes. Semver will keep it automagically up to date until 2.0.0 anyways.

**Comment by timkelty** [comment]
Ok, good to know. Thanks!
