### ISSUE TITLE
Loading config file error is undescriptive

### ISSUE THREAD

**Issue by rahatarmanahmed** [jscs-dev/gulp-jscs#79]
https://github.com/jscs-dev/gulp-jscs/blob/master/index.js#L36
This completely ignores the error received from jscs. In my case, I had a formatting issue and the error had a message explaining where the error was. I had to edit gulp-jscs to output the error to see it, however.

**Comment by sindresorhus** [comment]
I wasn't able to reproduce any config file loading failure, but if you want to prevent any future regression, please submit a unit test ;)
