### ISSUE TITLE
Set base jscs to ^1.12.0

### ISSUE THREAD

**Issue by buzzedword** [jscs-dev/gulp-jscs#80]
I know there's been a few of these requests in the past, but I think 1.12.0 is significant enough to merit bumping the lower bounds of the `gulp-jscs` package.

Ideally, this would be to eventually support allowing options like auto-fixing through, considering thats a whopper of a feature to be missing through gulp.

**Comment by sindresorhus** [comment]
You and everone else seems to be confused about how semver works.

Read up: https://nodesource.com/blog/semver-tilde-and-caret

tl;dr There's no need for bumping, you'll get the latest `jscs` up until before `2.0.0`.

**Comment by buzzedword** [comment]
You answered me on twitter, anyway-- sorry! I know that semver will auto-upgrade with a `^` character-- I was proposing bumping the contract in your package.json to state you support from 1.12.0 onward.

Use case here meaning, if I was an absolute stickler for package.json formats, and at some point you allow using flags available in later versions, updating the semver here would allow me to see up to what API version you've verified things working.

This is less about what version is packaged and more of, "What flags can I actually pass in?"
