### ISSUE TITLE
gulp-jscs should support v2.1.0 of jscs

### ISSUE THREAD

**Issue by Drarok** [jscs-dev/gulp-jscs#90]
JSCS have [released v2.1.0][jscs v2.1.0], it would be nice if I could use that from gulp-jscs.

[jscs v2.1.0]: https://github.com/jscs-dev/node-jscs/releases/tag/v2.1.0

**Comment by sindresorhus** [comment]
Sure would be nice if people could learn semver...

https://github.com/jscs-dev/gulp-jscs/issues/86 https://github.com/jscs-dev/gulp-jscs/issues/80 https://github.com/jscs-dev/gulp-jscs/pull/73 https://github.com/jscs-dev/gulp-jscs/pull/68 https://github.com/jscs-dev/gulp-jscs/issues/67 https://github.com/jscs-dev/gulp-jscs/issues/61 https://github.com/jscs-dev/gulp-jscs/pull/59 https://github.com/jscs-dev/gulp-jscs/pull/45 https://github.com/jscs-dev/gulp-jscs/issues/44 https://github.com/jscs-dev/gulp-jscs/pull/32 https://github.com/jscs-dev/gulp-jscs/pull/25

Read up on https://nodesource.com/blog/semver-tilde-and-caret ;)

**Comment by Drarok** [comment]
_sigh_… sorry. We were discussing semver earlier today and I _still_ got it wrong!
