### ISSUE TITLE
Can't get it to write fixed files back to system

### ISSUE THREAD

**Issue by andrewconnell** [jscs-dev/gulp-jscs#91]
No problems running the plugin to analyze my code using the following task. However when I add `fix:true`, nothing changes in the files and JSCS now acts like it isn't running at all... when I remove the object passed into the JSCS plugin and remove the `gulp.dest()` line, it will report code style issues.

So, it seems either passing in the `fix:true` or tying to write back the fixed files causes JSCS to short circuit internally... ideas?

```javascript
var $ = require('gulp-load-plugins')({lazy: true});
gulp.task('vet', function () {
  log('Analyzing source with JSHint and JSCS');

  return gulp
    .src(config.allJs, {base: './'})
    .pipe($.jshint())
    .pipe($.jshint.reporter('jshint-stylish', {verbose: true}))
    .pipe($.jscs({fix:true}))
    .pipe(gulp.dest('./'));
});
```

**Comment by sindresorhus** [comment]
Try version [3.0.0](https://github.com/jscs-dev/gulp-jscs/releases/tag/v3.0.0). Happy to look into this more if you submit a failing test, but according to our [test](https://github.com/jscs-dev/gulp-jscs/blob/002c9b56fb0c6742d68759434755771fd540c0f3/test.js#L130) it's working fine.
